version: '3.5'

services:
  postgres:
    container_name: postgres_container_auth_jwt
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
    volumes:
       - postgres_auth_jwt:/data/postgres
    ports:
      - "5433:5432"
    networks:
      - postgres_auth_jwt
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container_auth_jwt
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin_auth_jwt:/root/.pgadmin

    ports:
      - "${PGADMIN_PORT:-8090}:80"
    networks:
      - postgres_auth_jwt
    restart: unless-stopped

networks:
  postgres_auth_jwt:
    driver: bridge

volumes:
    postgres_auth_jwt:
    pgadmin_auth_jwt:
